# Block 5 Exercise 1: Classification

## MNIST Data
In these exercises we are using the MNIST data set on handwritten digits to compare supervised classification algorithms...   

In [1]:
#imports 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import fetch_openml

In [2]:
# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)


In [3]:
#the full MNIST data set contains 70k samples of digits 0-9 as 28*28 gray scale images (represented as 784 dim vectors)
np.shape(X)

(70000, 784)

### E1.1: Use SkLearn methods to split the MNIST data into random train and test sets. Use 60k samples for training.  


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1) #split 90% train 10% test

### E1.2: Train models on the train data.
Train the following models with default parameters on the train data.
* [Naive Bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB) (assuming a Gaussian distribution of the data)
* [Simple linear model](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier)
   * use ``loss='log'`` to reproduce our logistic loss function 
* [Random Forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)

Compare the training accuracy (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score) and [confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html#sklearn.metrics.confusion_matrix) for all three models.

In [5]:
#define models
from sklearn.naive_bayes import GaussianNB
from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier

bayes=GaussianNB()
linear=linear_model.SGDClassifier(loss='log', max_iter=50) #limit number of iterations -> linear model will not converge
rf=RandomForestClassifier()

#now train all

In [6]:
%%time
bayes.fit(X_train,y_train)

CPU times: user 1.07 s, sys: 588 ms, total: 1.66 s
Wall time: 1.74 s


GaussianNB()

In [7]:
%%time
linear.fit(X_train,y_train)

CPU times: user 1min 7s, sys: 54.2 ms, total: 1min 7s
Wall time: 1min 7s


/home/keuper/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py:577: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(loss='log', max_iter=50)

In [8]:
%%time
rf.fit(X_train,y_train)

CPU times: user 59.3 s, sys: 19.4 ms, total: 59.3 s
Wall time: 59.4 s


RandomForestClassifier()

In [9]:
#train error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [10]:
%%time
#Bayes
accuracy_score(y_train,bayes.predict(X_train))

CPU times: user 2.26 s, sys: 1.23 s, total: 3.49 s
Wall time: 3.5 s


0.5544126984126985

In [18]:
#test
accuracy_score(y_test,bayes.predict(X_test))

0.5561428571428572

In [17]:
confusion_matrix(y_test,bayes.predict(X_test))

array([[669,   2,   4,   4,   1,   1,  17,   1,  30,  11],
       [  1, 733,   3,   2,   0,   0,   5,   1,  30,  11],
       [ 86,  22, 190,  42,   0,   0, 170,   3, 157,  13],
       [ 60,  35,   7, 214,   1,   1,  43,   9, 256,  70],
       [ 26,   3,   5,   2,  95,   5,  65,   3, 134, 314],
       [ 90,  11,   7,  14,   2,  31,  33,   1, 379,  67],
       [  7,   7,   2,   0,   0,   2, 658,   0,  14,   1],
       [  3,   5,   4,   3,   8,   0,   1, 212,  31, 446],
       [ 10,  81,   2,   4,   5,   4,  13,   1, 421, 160],
       [  5,   5,   1,   2,   6,   0,   0,   4,  10, 670]])

In [12]:
%%time
#Linear
accuracy_score(y_train,linear.predict(X_train))

CPU times: user 479 ms, sys: 13.8 ms, total: 493 ms
Wall time: 208 ms


0.8758571428571429

In [19]:
#train
accuracy_score(y_test,linear.predict(X_test))

0.8554285714285714

In [20]:
confusion_matrix(y_test,linear.predict(X_test))

array([[607,   0,  14,   1,   5,  21,  36,   5,  49,   2],
       [  0, 728,   4,   0,   1,   8,   2,   2,  39,   2],
       [  2,   4, 580,   1,   7,   5,  12,  16,  55,   1],
       [  0,   2,  30, 474,   1,  72,  13,  20,  80,   4],
       [  0,   2,   5,   2, 579,   1,  15,   1,  21,  26],
       [  1,   2,   4,   7,  10, 553,  19,   3,  31,   5],
       [  0,   4,   7,   0,   2,  15, 657,   0,   6,   0],
       [  0,   1,   8,   0,   8,   4,   2, 659,  12,  19],
       [  0,   6,  12,   1,   1,  50,  10,   6, 608,   7],
       [  0,   3,   4,   1,  25,  18,   2,  50,  57, 543]])

In [22]:
%%time
#random Forest
accuracy_score(y_train,rf.predict(X_train))

CPU times: user 3.18 s, sys: 9.31 ms, total: 3.19 s
Wall time: 3.19 s


1.0

In [21]:
accuracy_score(y_test,rf.predict(X_test))

0.9675714285714285

In [15]:
confusion_matrix(y_test,rf.predict(X_test))

array([[727,   0,   0,   0,   2,   3,   4,   2,   1,   1],
       [  0, 773,   3,   1,   4,   2,   1,   1,   1,   0],
       [  5,   1, 658,   5,   3,   0,   0,   4,   6,   1],
       [  0,   0,  12, 663,   0,   6,   0,   5,   7,   3],
       [  2,   0,   0,   0, 631,   0,   6,   0,   3,  10],
       [  0,   1,   0,  10,   2, 610,   5,   0,   6,   1],
       [  2,   2,   1,   0,   1,   4, 681,   0,   0,   0],
       [  0,   3,   6,   0,   5,   0,   0, 688,   4,   7],
       [  0,   2,   6,   4,   4,   3,   4,   1, 671,   6],
       [  4,   5,   0,   6,   4,   2,   1,   7,   3, 671]])