# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [1]:
import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [2]:
zeros = np.zeros(10)

In [3]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))

In [5]:
print("Size of the array: ",
      Z.size)
 
print("Memory size of one array element in bytes: ",
      Z.itemsize)
 
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      Z.size * Z.itemsize)

Size of the array:  100
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 800


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Y = np.arange(10,50)
Y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
np.flip(Z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
A = np.arange(0, 9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
B = np.array([1,2,0,0,4,0])
np.argwhere(B != 0)

array([[0],
       [1],
       [4]])

#### 8) Create a 3x3 identity matrix (★☆☆)

In [11]:
C = np.identity(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

In [12]:
D = np.random.random((3,3,3))
D

array([[[0.18383674, 0.02315238, 0.66270533],
        [0.60462002, 0.30246291, 0.94683692],
        [0.43500575, 0.79932104, 0.42868303]],

       [[0.30914608, 0.5044212 , 0.8886729 ],
        [0.01439509, 0.91005372, 0.48047273],
        [0.21880677, 0.42237067, 0.78305024]],

       [[0.77657798, 0.71603707, 0.91557933],
        [0.2976145 , 0.63380939, 0.3046753 ],
        [0.83117916, 0.30424617, 0.43076475]]])

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
E = np.random.random((10,10))
E

array([[0.22262573, 0.04966589, 0.86161116, 0.42150647, 0.42400898,
        0.13014369, 0.40419934, 0.18844312, 0.43394957, 0.75758485],
       [0.9167422 , 0.01206251, 0.0237194 , 0.57568604, 0.89957818,
        0.99405602, 0.69959508, 0.50768151, 0.09857101, 0.57240335],
       [0.06266003, 0.8788865 , 0.56323898, 0.59886853, 0.21941242,
        0.05869193, 0.69788865, 0.25989318, 0.52683109, 0.34453903],
       [0.32393322, 0.86655772, 0.15015522, 0.12476887, 0.45397743,
        0.79950665, 0.05585563, 0.34364475, 0.77671808, 0.40619814],
       [0.06518608, 0.89029659, 0.1049794 , 0.30332719, 0.41767093,
        0.61693522, 0.58745544, 0.17847565, 0.21580276, 0.74561852],
       [0.24420149, 0.60153162, 0.72322604, 0.73389919, 0.99751847,
        0.00498792, 0.73549692, 0.29543434, 0.31004123, 0.65620506],
       [0.63718424, 0.57509869, 0.05426849, 0.77484562, 0.02444466,
        0.82133031, 0.33997155, 0.70738384, 0.35240173, 0.68333918],
       [0.63674021, 0.01919118, 0.8482432

In [14]:
E.max()

0.9975184737989694

In [15]:
E.min()

0.00443300437914429

#### 11) Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
F = np.random.random(30)
F

array([0.83308269, 0.84833261, 0.20116409, 0.30564793, 0.60948566,
       0.76486145, 0.40540915, 0.32880121, 0.78395903, 0.72821741,
       0.6194811 , 0.67480954, 0.82513684, 0.01376941, 0.66679313,
       0.06526365, 0.94977067, 0.01479432, 0.26617308, 0.18590971,
       0.27087784, 0.68078627, 0.95808179, 0.76244721, 0.02731874,
       0.03452655, 0.86976207, 0.38134759, 0.0314703 , 0.533163  ])

In [17]:
F.mean()

0.48802146706363836

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 14) Predict (before executig) the results of the following expressions? (★☆☆)

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
G = np.zeros((5, 5), dtype=int)
np.fill_diagonal(G[1:], [1, 2, 3, 4])
print(G)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 17) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 18) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
Z[(Z>=3) & (Z<=8)] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 20. How to find common values between two arrays? (★☆☆)

In [28]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
np.intersect1d(Z1, Z2)

[4 6 8 2 5 4 8 0 6 2]
[2 6 0 4 2 7 6 8 0 9]


array([0, 2, 4, 6, 8])

#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [29]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 22) Extract the integer part of a random array (★★☆)

In [30]:
Z = np.random.uniform(0,10,10)
print(Z)

# print(Z - Z%1)
# print(np.floor(Z))
# print(np.ceil(Z)-1)
print(Z.astype(int))
# print(np.trunc(Z))

[3.86257838 4.07871408 2.50568777 9.23170212 4.69043758 9.2299171
 8.00952619 3.13197513 0.94703064 7.14468087]
[3 4 2 9 4 9 8 3 0 7]


#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
Z = np.zeros((5,5))

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [32]:
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [43]:
# linspace hat 0 (start) & 1 (stop) enthalten, d.h. man braucht 12 Ziffern --> am Ende nur zweites bis zweitletzes Element
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
# # alternativ
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26) Create a random vector of size 10 and sort it (★★☆)

In [44]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01928386 0.18931008 0.27211257 0.37263097 0.44460084 0.45208674
 0.52743651 0.64258344 0.79420054 0.98812956]


#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[0 1 0 0 0]
[1 1 0 1 1]
False
False


#### 28) Make an array immutable (read-only) (★★☆)

In [46]:
Z = np.zeros(10)

Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
Z = np.random.random(10)

print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.73037001 0.99247236 0.14734115 0.19860804 0.73934503 0.98918258
 0.35309844 0.22862323 0.19488901 0.19516943]
[0.73037001 0.         0.14734115 0.19860804 0.73934503 0.98918258
 0.35309844 0.22862323 0.19488901 0.19516943]


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [48]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [49]:
n = 10
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [50]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.25230697 -0.11532027  0.25028063 -0.27466852 -0.1614413  -0.22599579
   0.29586308 -0.03519498  0.37623313 -0.36206294]
 [-0.24079243  0.43040285 -0.06813133  0.39382824 -0.30317116 -0.11242474
  -0.35676196 -0.26451485  0.25273004  0.26883536]
 [-0.39902611 -0.29827926 -0.04606892  0.51354661  0.2987045   0.35874279
  -0.40803238 -0.40100697 -0.0211643   0.40258403]
 [ 0.58931922 -0.18415388 -0.2857415  -0.1947874  -0.11296645 -0.22393249
   0.34681775  0.58530025 -0.16868017 -0.35117532]
 [ 0.15376187 -0.14217487  0.20858197  0.23261079 -0.02535093  0.06580952
  -0.17158953 -0.47249156  0.05336652  0.09747621]]


#### 33) sort an array by the 1st column? (★★☆)

In [51]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 1 5]
 [2 4 3]
 [9 4 3]]
[[7 1 5]
 [2 4 3]
 [9 4 3]]


#### 34) Find the nearest value from a given value z  in an array Z(★★☆)

In [52]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.23509218 0.30784889 0.50514452 0.60780854 0.3751835  0.34586902
 0.88257687 0.20025162 0.24539689 0.69481845]
0.5051445189988013


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [53]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

print(A)
print(B)

print('-'*30)

# Efficient multi-dimensional iterator object to iterate over arrays.
it = np.nditer([A,B,None])

for x,y,z in it:
    z[...] = x + y

print(it.operands[2]) # 2 identifziert None
# it.operands[0] = A
# it.operands[1] = B

[[0]
 [1]
 [2]]
[[0 1 2]]
------------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [54]:
Z = np.random.randint(0,10,50)
print(Z)

print(np.bincount(Z).argmax())

[8 9 3 8 0 9 8 8 7 3 2 5 2 5 9 9 4 3 2 6 7 8 3 6 8 1 0 8 9 0 8 8 6 1 8 5 7
 5 3 2 4 4 9 9 0 0 7 7 9 0]
8


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [55]:
Z = np.random.randint(0,2,(6,3))
print(Z)

print(np.ascontiguousarray(Z))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
# print(uZ)

[[0 0 1]
 [0 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 0]]
[[0 0 1]
 [0 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 0]]
