# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [ ]:
import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [ ]:
zeros = np.zeros(10)

In [ ]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [ ]:
Z = np.zeros((10,10))

In [ ]:
print("Size of the array: ",
      Z.size)
 
print("Memory size of one array element in bytes: ",
      Z.itemsize)
 
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      Z.size * Z.itemsize)

Size of the array:  100
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 800


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Y = np.arange(10,50)
Y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = np.arange(50)
np.flip(Z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
A = np.arange(0, 9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
B = np.array([1,2,0,0,4,0])
np.argwhere(B == 0)

array([[2],
       [3],
       [5]])

#### 8) Create a 3x3 identity matrix (★☆☆)

In [ ]:
C = np.identity(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

In [ ]:
D = np.random.random((3,3,3))
D

array([[[0.80334276, 0.13612323, 0.623141  ],
        [0.41733602, 0.9150861 , 0.84631137],
        [0.63426521, 0.33014661, 0.81319858]],

       [[0.11610223, 0.22089016, 0.88298661],
        [0.51425623, 0.78538623, 0.16676861],
        [0.79210506, 0.75497392, 0.28297648]],

       [[0.62440161, 0.21097982, 0.46208046],
        [0.28085675, 0.53591134, 0.20980106],
        [0.2143686 , 0.17381695, 0.70247395]]])

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
E = np.random.random((10,10))
E

array([[0.49215354, 0.63888465, 0.77078218, 0.40638654, 0.30069384,
        0.28571404, 0.20309872, 0.14845586, 0.28079191, 0.15102914],
       [0.24060856, 0.41263275, 0.81583283, 0.53055642, 0.14066091,
        0.37979739, 0.59543694, 0.77187732, 0.94430046, 0.79334803],
       [0.27326825, 0.08785812, 0.48492645, 0.57666193, 0.1091698 ,
        0.85311165, 0.19428712, 0.35745761, 0.32012104, 0.15626494],
       [0.05328847, 0.00744671, 0.97523776, 0.92014403, 0.28879356,
        0.11449843, 0.4784444 , 0.74248827, 0.68307635, 0.26250528],
       [0.43959859, 0.19534746, 0.54332475, 0.55974297, 0.95288621,
        0.67138117, 0.07004209, 0.91108576, 0.63798418, 0.75696973],
       [0.64109828, 0.18938634, 0.36713152, 0.63162388, 0.09942181,
        0.39706679, 0.40514005, 0.95876112, 0.64487272, 0.85974161],
       [0.49906694, 0.61434135, 0.96860304, 0.79506275, 0.53084907,
        0.45732583, 0.50830183, 0.26871815, 0.17565253, 0.977753  ],
       [0.31172594, 0.76056532, 0.0388187

In [ ]:
E.max()

0.9777529954494242

In [ ]:
E.min()

0.0026176093812592116

#### 11) Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
F = np.random.random(30)
F

array([0.49562044, 0.01086879, 0.5625321 , 0.40487512, 0.05778517,
       0.77368709, 0.29499888, 0.76006464, 0.23352675, 0.59066351,
       0.66671767, 0.056532  , 0.06372125, 0.54763243, 0.58967359,
       0.86800514, 0.217454  , 0.84856315, 0.68752263, 0.95183021,
       0.28643124, 0.42501399, 0.31015809, 0.71924431, 0.82987417,
       0.58630329, 0.2767672 , 0.18342222, 0.20296146, 0.19373186])

In [ ]:
F.mean()

0.45653941340748644

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 14) Predict (before executig) the results of the following expressions? (★☆☆)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
G = np.diag([1, 2, 3, 4, 5])
G

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 17) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 18) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
Z[(Z>=3) & (Z<=8)] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 20. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
np.intersect1d(Z1, Z2)

[0 6 7 1 1 7 6 8 2 2]
[9 3 6 5 8 4 7 3 2 2]


array([2, 6, 7, 8])

#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 22) Extract the integer part of a random array (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)

# print(Z - Z%1)
# print(np.floor(Z))
# print(np.ceil(Z)-1)
print(Z.astype(int))
# print(np.trunc(Z))

[9.72087309 8.67777203 7.15410186 7.72501026 5.51929544 8.58344245
 7.58666891 0.80768693 2.67438415 2.06713721]
[9 8 7 7 5 8 7 0 2 2]


#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
# linspace hat 0 (start) & 1 (stop) enthalten, d.h. man braucht 12 Ziffern --> am Ende nur zweites bis zweitletzes Element
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26) Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03390483 0.08069634 0.22333308 0.2887756  0.70870855 0.72101355
 0.72411509 0.84004814 0.89529521 0.93247966]


#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[0 0 0 1 1]
[1 0 1 1 1]
False
False


#### 28) Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)

Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)

print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.23372491 0.82565288 0.90032993 0.57971128 0.26476773 0.48642849
 0.33693817 0.10788259 0.47439846 0.40349412]
[0.23372491 0.82565288 0.         0.57971128 0.26476773 0.48642849
 0.33693817 0.10788259 0.47439846 0.40349412]


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.1200747   0.27801922 -0.23684606 -0.10779571  0.27039219 -0.32927521
   0.49298568 -0.23471982 -0.21145397 -0.04138101]
 [-0.3491007  -0.05569697  0.02456137  0.19706212 -0.03140794  0.41918559
  -0.00366414  0.16382274 -0.54031476  0.17555269]
 [-0.01160535 -0.05246964 -0.41648826  0.26574037  0.17953177 -0.06729243
   0.41517075 -0.35954463 -0.06659796  0.11355537]
 [ 0.39776109 -0.34107106 -0.16611472 -0.04815277 -0.11972803  0.16929756
   0.46287032 -0.31633609  0.12934381 -0.16787012]
 [ 0.29358628  0.09740688 -0.13185598  0.22693702  0.3888215  -0.10601563
  -0.40214915 -0.36070655  0.13561189 -0.14163626]]


#### 33) sort an array by the 1st column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 8 4]
 [0 1 0]
 [5 4 6]]
[[0 1 0]
 [5 4 6]
 [5 8 4]]


#### 34) Find the nearest value from a given value z  in an array Z(★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.74704581 0.79157189 0.33917538 0.42250422 0.79321862 0.15206566
 0.53189637 0.06722964 0.22677192 0.98738929]
0.5318963662439543


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

print(A)
print(B)

print('-'*30)

# Efficient multi-dimensional iterator object to iterate over arrays.
it = np.nditer([A,B,None])

for x,y,z in it:
    z[...] = x + y

print(it.operands[2]) # 2 identifziert None
# it.operands[0] = A
# it.operands[1] = B

[[0]
 [1]
 [2]]
[[0 1 2]]
------------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)

print(np.bincount(Z).argmax())

[9 6 7 3 2 7 4 8 9 2 0 1 5 4 3 1 5 9 8 5 2 5 4 8 6 2 4 7 9 5 1 9 9 9 8 8 5
 1 5 6 4 7 2 8 1 4 0 3 5 3]
5


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
print(Z)

print(np.ascontiguousarray(Z))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
# print(uZ)

[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 0 0]]
[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 0 0]]
